name: "Whisper Openapi Deploy ${{ parameters.environmentName }}"

trigger:
  - main

pool:
  vmImage: ubuntu-latest

parameters:
  - name: environmentName
    type: string
    default: "dev"
    values:
      - "dev"

  - name: infraComponents
    type: object
    default:
      - container-registry
      - networking

  - name: appComponents
    type: object
    default:
      - whisper

variables:
  - group: tools-versions
  - group: azure-variables
  - group: acr-credentials
  - name: target
    value: $(build.artifactstagingdirectory)/terraform
  - name: artifact
    value: ${{ parameters.environmentName }} - Terraform
  - group: acr-credentials
  
stages:
  - template: templates/deploy.yaml
    parameters:
      infraComponents: ${{ parameters.infraComponents }}
      appComponents: ${{ parameters.appComponents }}
      environmentName: ${{ parameters.environmentName }}
