name: "Whisper Openapi Deploy ${{ parameters.environmentName }}"

trigger:
  - main

pool:
  vmImage: ubuntu-latest

parameters:
  - name: environmentName
    type: string
    default: "dev"
    values:
      - "dev"

variables:
  - group: tools-versions
  - group: azure-variables
  - name: target
    value: $(build.artifactstagingdirectory)/terraform
  - name: artifact
    value: ${{ parameters.environmentName }} - Terraform
  
stages:
  - template: templates/deploy.yaml
    parameters:
      environmentName: ${{ parameters.environmentName }}
